#!/usr/bin/env ruby

pondDir = File.expand_path "/usr/local/lib/pond"

ENV['BUNDLE_GEMFILE'] ||= pondDir + "/Gemfile"
$:.unshift pondDir

require 'bundler/setup'
require 'pond'

Pond.go ARGV[0], ARGV[1]
